# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1000, 800)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.nodesVerticalLayout = QtGui.QVBoxLayout()
        self.nodesVerticalLayout.setObjectName(_fromUtf8("nodesVerticalLayout"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.nodesVerticalLayout.addWidget(self.label_2)
        self.connectedNodesListWidget = QtGui.QListWidget(self.centralwidget)
        self.connectedNodesListWidget.setObjectName(_fromUtf8("connectedNodesListWidget"))
        self.nodesVerticalLayout.addWidget(self.connectedNodesListWidget)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.nodesVerticalLayout.addWidget(self.label)
        self.visibleNodesListWidget = QtGui.QListWidget(self.centralwidget)
        self.visibleNodesListWidget.setObjectName(_fromUtf8("visibleNodesListWidget"))
        self.nodesVerticalLayout.addWidget(self.visibleNodesListWidget)
        self.connectDisconnectNodeBtn = QtGui.QPushButton(self.centralwidget)
        self.connectDisconnectNodeBtn.setObjectName(_fromUtf8("connectDisconnectNodeBtn"))
        self.nodesVerticalLayout.addWidget(self.connectDisconnectNodeBtn)
        self.horizontalLayout.addLayout(self.nodesVerticalLayout)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.statusTab = QtGui.QWidget()
        self.statusTab.setObjectName(_fromUtf8("statusTab"))
        self.gridLayout = QtGui.QGridLayout(self.statusTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.statusInformationGroupBox = QtGui.QGroupBox(self.statusTab)
        self.statusInformationGroupBox.setObjectName(_fromUtf8("statusInformationGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.statusInformationGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lastIdBroadcastLabel = QtGui.QLabel(self.statusInformationGroupBox)
        self.lastIdBroadcastLabel.setObjectName(_fromUtf8("lastIdBroadcastLabel"))
        self.gridLayout_2.addWidget(self.lastIdBroadcastLabel, 0, 0, 1, 1)
        self.lastIdBroadcastIndicator = QtGui.QLabel(self.statusInformationGroupBox)
        self.lastIdBroadcastIndicator.setObjectName(_fromUtf8("lastIdBroadcastIndicator"))
        self.gridLayout_2.addWidget(self.lastIdBroadcastIndicator, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.statusInformationGroupBox, 0, 0, 1, 1)
        self.debugLogGroupBox = QtGui.QGroupBox(self.statusTab)
        self.debugLogGroupBox.setObjectName(_fromUtf8("debugLogGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.debugLogGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.debugLogPlainTextEdit = QtGui.QPlainTextEdit(self.debugLogGroupBox)
        self.debugLogPlainTextEdit.setReadOnly(True)
        self.debugLogPlainTextEdit.setObjectName(_fromUtf8("debugLogPlainTextEdit"))
        self.verticalLayout.addWidget(self.debugLogPlainTextEdit)
        self.gridLayout.addWidget(self.debugLogGroupBox, 1, 0, 1, 1)
        self.tabWidget.addTab(self.statusTab, _fromUtf8(""))
        self.nodeSettingsTab = QtGui.QWidget()
        self.nodeSettingsTab.setObjectName(_fromUtf8("nodeSettingsTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.nodeSettingsTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.nodeIdLineEdit = QtGui.QLineEdit(self.nodeSettingsTab)
        self.nodeIdLineEdit.setObjectName(_fromUtf8("nodeIdLineEdit"))
        self.gridLayout_3.addWidget(self.nodeIdLineEdit, 0, 1, 1, 1)
        self.nodeIdEditLabel = QtGui.QLabel(self.nodeSettingsTab)
        self.nodeIdEditLabel.setObjectName(_fromUtf8("nodeIdEditLabel"))
        self.gridLayout_3.addWidget(self.nodeIdEditLabel, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_10 = QtGui.QLabel(self.nodeSettingsTab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_3.addWidget(self.label_10)
        self.saveNodeSettingsBtn = QtGui.QPushButton(self.nodeSettingsTab)
        self.saveNodeSettingsBtn.setObjectName(_fromUtf8("saveNodeSettingsBtn"))
        self.verticalLayout_3.addWidget(self.saveNodeSettingsBtn)
        self.tabWidget.addTab(self.nodeSettingsTab, _fromUtf8(""))
        self.actionsTab = QtGui.QWidget()
        self.actionsTab.setObjectName(_fromUtf8("actionsTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.actionsTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget_2 = QtGui.QTabWidget(self.actionsTab)
        self.tabWidget_2.setEnabled(True)
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.actionsCanLoggerTab = QtGui.QWidget()
        self.actionsCanLoggerTab.setObjectName(_fromUtf8("actionsCanLoggerTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.actionsCanLoggerTab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.filterFramesGroupBox = QtGui.QGroupBox(self.actionsCanLoggerTab)
        self.filterFramesGroupBox.setObjectName(_fromUtf8("filterFramesGroupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.filterFramesGroupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.filterFramesByIdLineEdit = QtGui.QLineEdit(self.filterFramesGroupBox)
        self.filterFramesByIdLineEdit.setText(_fromUtf8(""))
        self.filterFramesByIdLineEdit.setObjectName(_fromUtf8("filterFramesByIdLineEdit"))
        self.gridLayout_4.addWidget(self.filterFramesByIdLineEdit, 0, 1, 1, 1)
        self.filterFramesByIdCheckbox = QtGui.QCheckBox(self.filterFramesGroupBox)
        self.filterFramesByIdCheckbox.setObjectName(_fromUtf8("filterFramesByIdCheckbox"))
        self.gridLayout_4.addWidget(self.filterFramesByIdCheckbox, 0, 0, 1, 1)
        self.filterFramesByNewFramesAfterCheckbox = QtGui.QCheckBox(self.filterFramesGroupBox)
        self.filterFramesByNewFramesAfterCheckbox.setObjectName(_fromUtf8("filterFramesByNewFramesAfterCheckbox"))
        self.gridLayout_4.addWidget(self.filterFramesByNewFramesAfterCheckbox, 1, 0, 1, 1)
        self.filterFramesAfterNSpinBox = QtGui.QSpinBox(self.filterFramesGroupBox)
        self.filterFramesAfterNSpinBox.setMaximum(10000)
        self.filterFramesAfterNSpinBox.setObjectName(_fromUtf8("filterFramesAfterNSpinBox"))
        self.gridLayout_4.addWidget(self.filterFramesAfterNSpinBox, 1, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.filterFramesGroupBox)
        self.canLogSettingsGroupBox = QtGui.QGroupBox(self.actionsCanLoggerTab)
        self.canLogSettingsGroupBox.setObjectName(_fromUtf8("canLogSettingsGroupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.canLogSettingsGroupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.canLogOnPort1RadioBtn = QtGui.QRadioButton(self.canLogSettingsGroupBox)
        self.canLogOnPort1RadioBtn.setChecked(True)
        self.canLogOnPort1RadioBtn.setObjectName(_fromUtf8("canLogOnPort1RadioBtn"))
        self.gridLayout_5.addWidget(self.canLogOnPort1RadioBtn, 1, 0, 1, 1)
        self.canLogOnPort2RadioBtn = QtGui.QRadioButton(self.canLogSettingsGroupBox)
        self.canLogOnPort2RadioBtn.setEnabled(False)
        self.canLogOnPort2RadioBtn.setObjectName(_fromUtf8("canLogOnPort2RadioBtn"))
        self.gridLayout_5.addWidget(self.canLogOnPort2RadioBtn, 2, 0, 1, 1)
        self.passThruModeCheckBox = QtGui.QCheckBox(self.canLogSettingsGroupBox)
        self.passThruModeCheckBox.setEnabled(False)
        self.passThruModeCheckBox.setObjectName(_fromUtf8("passThruModeCheckBox"))
        self.gridLayout_5.addWidget(self.passThruModeCheckBox, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.canLogSettingsGroupBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.canLogTableView = CanLogTableView(self.actionsCanLoggerTab)
        self.canLogTableView.setObjectName(_fromUtf8("canLogTableView"))
        self.verticalLayout_4.addWidget(self.canLogTableView)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.saveCanLogBtn = QtGui.QToolButton(self.actionsCanLoggerTab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/save.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveCanLogBtn.setIcon(icon)
        self.saveCanLogBtn.setObjectName(_fromUtf8("saveCanLogBtn"))
        self.horizontalLayout_2.addWidget(self.saveCanLogBtn)
        self.startCanLoggerBtn = QtGui.QPushButton(self.actionsCanLoggerTab)
        self.startCanLoggerBtn.setObjectName(_fromUtf8("startCanLoggerBtn"))
        self.horizontalLayout_2.addWidget(self.startCanLoggerBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.tabWidget_2.addTab(self.actionsCanLoggerTab, _fromUtf8(""))
        self.actionsReplayTab = QtGui.QWidget()
        self.actionsReplayTab.setObjectName(_fromUtf8("actionsReplayTab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.actionsReplayTab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_2 = QtGui.QGroupBox(self.actionsReplayTab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.replayMoveUpBtn = QtGui.QToolButton(self.groupBox_2)
        self.replayMoveUpBtn.setObjectName(_fromUtf8("replayMoveUpBtn"))
        self.horizontalLayout_8.addWidget(self.replayMoveUpBtn)
        self.replayMoveDownBtn = QtGui.QToolButton(self.groupBox_2)
        self.replayMoveDownBtn.setObjectName(_fromUtf8("replayMoveDownBtn"))
        self.horizontalLayout_8.addWidget(self.replayMoveDownBtn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.replayRemoveFrameBtn = QtGui.QPushButton(self.groupBox_2)
        self.replayRemoveFrameBtn.setEnabled(False)
        self.replayRemoveFrameBtn.setObjectName(_fromUtf8("replayRemoveFrameBtn"))
        self.horizontalLayout_8.addWidget(self.replayRemoveFrameBtn)
        self.addReplayFrameBtn = QtGui.QPushButton(self.groupBox_2)
        self.addReplayFrameBtn.setEnabled(True)
        self.addReplayFrameBtn.setObjectName(_fromUtf8("addReplayFrameBtn"))
        self.horizontalLayout_8.addWidget(self.addReplayFrameBtn)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.replayFramesTableView = QtGui.QTableView(self.groupBox_2)
        self.replayFramesTableView.setObjectName(_fromUtf8("replayFramesTableView"))
        self.verticalLayout_10.addWidget(self.replayFramesTableView)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.actionsReplayTab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_11.addWidget(self.label_19)
        self.replayFrameIdLineEdit = QtGui.QLineEdit(self.groupBox)
        self.replayFrameIdLineEdit.setEnabled(False)
        self.replayFrameIdLineEdit.setObjectName(_fromUtf8("replayFrameIdLineEdit"))
        self.verticalLayout_11.addWidget(self.replayFrameIdLineEdit)
        self.label_20 = QtGui.QLabel(self.groupBox)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_11.addWidget(self.label_20)
        self.replayPayloadLineEdit = QtGui.QLineEdit(self.groupBox)
        self.replayPayloadLineEdit.setEnabled(False)
        self.replayPayloadLineEdit.setObjectName(_fromUtf8("replayPayloadLineEdit"))
        self.verticalLayout_11.addWidget(self.replayPayloadLineEdit)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.startReplayBtn = QtGui.QPushButton(self.actionsReplayTab)
        self.startReplayBtn.setObjectName(_fromUtf8("startReplayBtn"))
        self.verticalLayout_7.addWidget(self.startReplayBtn)
        self.tabWidget_2.addTab(self.actionsReplayTab, _fromUtf8(""))
        self.actionsSecurityAccessTab = QtGui.QWidget()
        self.actionsSecurityAccessTab.setObjectName(_fromUtf8("actionsSecurityAccessTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.actionsSecurityAccessTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.securityHijackSecurityLevelSpinBox = QtGui.QSpinBox(self.actionsSecurityAccessTab)
        self.securityHijackSecurityLevelSpinBox.setEnabled(False)
        self.securityHijackSecurityLevelSpinBox.setObjectName(_fromUtf8("securityHijackSecurityLevelSpinBox"))
        self.gridLayout_6.addWidget(self.securityHijackSecurityLevelSpinBox, 5, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.actionsSecurityAccessTab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 6, 1, 1, 1)
        self.securityHijackStatusIndictor = QtGui.QLabel(self.actionsSecurityAccessTab)
        self.securityHijackStatusIndictor.setObjectName(_fromUtf8("securityHijackStatusIndictor"))
        self.gridLayout_6.addWidget(self.securityHijackStatusIndictor, 10, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.actionsSecurityAccessTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 4, 1, 1, 1)
        self.securityHijackToolIdLineEdit = QtGui.QLineEdit(self.actionsSecurityAccessTab)
        self.securityHijackToolIdLineEdit.setEnabled(False)
        self.securityHijackToolIdLineEdit.setObjectName(_fromUtf8("securityHijackToolIdLineEdit"))
        self.gridLayout_6.addWidget(self.securityHijackToolIdLineEdit, 1, 1, 1, 1)
        self.securityHijackNoOfAuthsToSkipSpinBox = QtGui.QSpinBox(self.actionsSecurityAccessTab)
        self.securityHijackNoOfAuthsToSkipSpinBox.setEnabled(False)
        self.securityHijackNoOfAuthsToSkipSpinBox.setObjectName(_fromUtf8("securityHijackNoOfAuthsToSkipSpinBox"))
        self.gridLayout_6.addWidget(self.securityHijackNoOfAuthsToSkipSpinBox, 7, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 9, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.actionsSecurityAccessTab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 2, 1, 1, 1)
        self.securityHijackTargetIdLineEdit = QtGui.QLineEdit(self.actionsSecurityAccessTab)
        self.securityHijackTargetIdLineEdit.setEnabled(False)
        self.securityHijackTargetIdLineEdit.setObjectName(_fromUtf8("securityHijackTargetIdLineEdit"))
        self.gridLayout_6.addWidget(self.securityHijackTargetIdLineEdit, 3, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.securityHijackUDSRadioButton = QtGui.QRadioButton(self.actionsSecurityAccessTab)
        self.securityHijackUDSRadioButton.setEnabled(False)
        self.securityHijackUDSRadioButton.setObjectName(_fromUtf8("securityHijackUDSRadioButton"))
        self.horizontalLayout_4.addWidget(self.securityHijackUDSRadioButton)
        self.securityHijackTPRadioButton = QtGui.QRadioButton(self.actionsSecurityAccessTab)
        self.securityHijackTPRadioButton.setEnabled(False)
        self.securityHijackTPRadioButton.setObjectName(_fromUtf8("securityHijackTPRadioButton"))
        self.horizontalLayout_4.addWidget(self.securityHijackTPRadioButton)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 8, 1, 1, 1)
        self.startSecurityHijackBtn = QtGui.QPushButton(self.actionsSecurityAccessTab)
        self.startSecurityHijackBtn.setEnabled(False)
        self.startSecurityHijackBtn.setObjectName(_fromUtf8("startSecurityHijackBtn"))
        self.gridLayout_6.addWidget(self.startSecurityHijackBtn, 11, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.actionsSecurityAccessTab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_6.addWidget(self.label_3, 0, 1, 1, 1)
        self.tabWidget_2.addTab(self.actionsSecurityAccessTab, _fromUtf8(""))
        self.actionsUDSTab = QtGui.QWidget()
        self.actionsUDSTab.setObjectName(_fromUtf8("actionsUDSTab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.actionsUDSTab)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_6 = QtGui.QLabel(self.actionsUDSTab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_8.addWidget(self.label_6)
        self.udsActionsComboBox = QtGui.QComboBox(self.actionsUDSTab)
        self.udsActionsComboBox.setEnabled(False)
        self.udsActionsComboBox.setObjectName(_fromUtf8("udsActionsComboBox"))
        self.verticalLayout_8.addWidget(self.udsActionsComboBox)
        self.udsActionContentsLayout = QtGui.QVBoxLayout()
        self.udsActionContentsLayout.setObjectName(_fromUtf8("udsActionContentsLayout"))
        self.verticalLayout_8.addLayout(self.udsActionContentsLayout)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_16 = QtGui.QLabel(self.actionsUDSTab)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_7.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.actionsUDSTab)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_7.addWidget(self.label_15, 0, 0, 1, 1)
        self.udsOwnIdLineEdit = QtGui.QLineEdit(self.actionsUDSTab)
        self.udsOwnIdLineEdit.setEnabled(False)
        self.udsOwnIdLineEdit.setObjectName(_fromUtf8("udsOwnIdLineEdit"))
        self.gridLayout_7.addWidget(self.udsOwnIdLineEdit, 0, 1, 1, 1)
        self.udsTargetIdLineEdit = QtGui.QLineEdit(self.actionsUDSTab)
        self.udsTargetIdLineEdit.setEnabled(False)
        self.udsTargetIdLineEdit.setObjectName(_fromUtf8("udsTargetIdLineEdit"))
        self.gridLayout_7.addWidget(self.udsTargetIdLineEdit, 1, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_7)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.newUDSSessionBtn = QtGui.QPushButton(self.actionsUDSTab)
        self.newUDSSessionBtn.setEnabled(False)
        self.newUDSSessionBtn.setObjectName(_fromUtf8("newUDSSessionBtn"))
        self.horizontalLayout_7.addWidget(self.newUDSSessionBtn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.label_13 = QtGui.QLabel(self.actionsUDSTab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_8.addWidget(self.label_13)
        self.udsLogPlainTextEdit = QtGui.QPlainTextEdit(self.actionsUDSTab)
        self.udsLogPlainTextEdit.setEnabled(False)
        self.udsLogPlainTextEdit.setReadOnly(True)
        self.udsLogPlainTextEdit.setObjectName(_fromUtf8("udsLogPlainTextEdit"))
        self.verticalLayout_8.addWidget(self.udsLogPlainTextEdit)
        self.tabWidget_2.addTab(self.actionsUDSTab, _fromUtf8(""))
        self.actionsTPTab = QtGui.QWidget()
        self.actionsTPTab.setObjectName(_fromUtf8("actionsTPTab"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.actionsTPTab)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_7 = QtGui.QLabel(self.actionsTPTab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_9.addWidget(self.label_7)
        self.tpActionsComboBox = QtGui.QComboBox(self.actionsTPTab)
        self.tpActionsComboBox.setEnabled(False)
        self.tpActionsComboBox.setObjectName(_fromUtf8("tpActionsComboBox"))
        self.verticalLayout_9.addWidget(self.tpActionsComboBox)
        self.tpActionContentsLayout = QtGui.QVBoxLayout()
        self.tpActionContentsLayout.setObjectName(_fromUtf8("tpActionContentsLayout"))
        self.verticalLayout_9.addLayout(self.tpActionContentsLayout)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.label_17 = QtGui.QLabel(self.actionsTPTab)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_9.addWidget(self.label_17)
        self.tpChannelNegotIdLineEdit = QtGui.QLineEdit(self.actionsTPTab)
        self.tpChannelNegotIdLineEdit.setEnabled(False)
        self.tpChannelNegotIdLineEdit.setObjectName(_fromUtf8("tpChannelNegotIdLineEdit"))
        self.verticalLayout_9.addWidget(self.tpChannelNegotIdLineEdit)
        self.label_18 = QtGui.QLabel(self.actionsTPTab)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_9.addWidget(self.label_18)
        self.tpModuleIdLineEdit = QtGui.QLineEdit(self.actionsTPTab)
        self.tpModuleIdLineEdit.setEnabled(False)
        self.tpModuleIdLineEdit.setObjectName(_fromUtf8("tpModuleIdLineEdit"))
        self.verticalLayout_9.addWidget(self.tpModuleIdLineEdit)
        self.newTPSessionBtn = QtGui.QPushButton(self.actionsTPTab)
        self.newTPSessionBtn.setEnabled(False)
        self.newTPSessionBtn.setObjectName(_fromUtf8("newTPSessionBtn"))
        self.verticalLayout_9.addWidget(self.newTPSessionBtn)
        self.label_14 = QtGui.QLabel(self.actionsTPTab)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_9.addWidget(self.label_14)
        self.tpLogPlainTextEdit = QtGui.QPlainTextEdit(self.actionsTPTab)
        self.tpLogPlainTextEdit.setEnabled(False)
        self.tpLogPlainTextEdit.setReadOnly(True)
        self.tpLogPlainTextEdit.setObjectName(_fromUtf8("tpLogPlainTextEdit"))
        self.verticalLayout_9.addWidget(self.tpLogPlainTextEdit)
        self.tabWidget_2.addTab(self.actionsTPTab, _fromUtf8(""))
        self.actionsMITMTab = QtGui.QWidget()
        self.actionsMITMTab.setObjectName(_fromUtf8("actionsMITMTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.actionsMITMTab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.rulesGroupBox = QtGui.QGroupBox(self.actionsMITMTab)
        self.rulesGroupBox.setObjectName(_fromUtf8("rulesGroupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.rulesGroupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.loadRulesFromFileBtn = QtGui.QToolButton(self.rulesGroupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/back-in-time.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadRulesFromFileBtn.setIcon(icon1)
        self.loadRulesFromFileBtn.setObjectName(_fromUtf8("loadRulesFromFileBtn"))
        self.horizontalLayout_6.addWidget(self.loadRulesFromFileBtn)
        self.saveRulesToFileBtn = QtGui.QToolButton(self.rulesGroupBox)
        self.saveRulesToFileBtn.setIcon(icon)
        self.saveRulesToFileBtn.setObjectName(_fromUtf8("saveRulesToFileBtn"))
        self.horizontalLayout_6.addWidget(self.saveRulesToFileBtn)
        self.saveRulesBtn = QtGui.QPushButton(self.rulesGroupBox)
        self.saveRulesBtn.setFlat(False)
        self.saveRulesBtn.setObjectName(_fromUtf8("saveRulesBtn"))
        self.horizontalLayout_6.addWidget(self.saveRulesBtn)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.removeRuleBtn = QtGui.QPushButton(self.rulesGroupBox)
        self.removeRuleBtn.setEnabled(False)
        self.removeRuleBtn.setObjectName(_fromUtf8("removeRuleBtn"))
        self.horizontalLayout_6.addWidget(self.removeRuleBtn)
        self.addRuleBtn = QtGui.QPushButton(self.rulesGroupBox)
        self.addRuleBtn.setObjectName(_fromUtf8("addRuleBtn"))
        self.horizontalLayout_6.addWidget(self.addRuleBtn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.rulesTableView = QtGui.QTableView(self.rulesGroupBox)
        self.rulesTableView.setObjectName(_fromUtf8("rulesTableView"))
        self.verticalLayout_6.addWidget(self.rulesTableView)
        self.verticalLayout_5.addWidget(self.rulesGroupBox)
        self.ruleSettingsGroupBox = QtGui.QGroupBox(self.actionsMITMTab)
        self.ruleSettingsGroupBox.setObjectName(_fromUtf8("ruleSettingsGroupBox"))
        self.gridLayout_9 = QtGui.QGridLayout(self.ruleSettingsGroupBox)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.conditionMessageIdLineEdit = QtGui.QLineEdit(self.ruleSettingsGroupBox)
        self.conditionMessageIdLineEdit.setEnabled(False)
        self.conditionMessageIdLineEdit.setMaxLength(4)
        self.conditionMessageIdLineEdit.setObjectName(_fromUtf8("conditionMessageIdLineEdit"))
        self.gridLayout_9.addWidget(self.conditionMessageIdLineEdit, 2, 1, 1, 1)
        self.actionMaskLineEdit = QtGui.QLineEdit(self.ruleSettingsGroupBox)
        self.actionMaskLineEdit.setEnabled(False)
        self.actionMaskLineEdit.setText(_fromUtf8(""))
        self.actionMaskLineEdit.setMaxLength(80)
        self.actionMaskLineEdit.setCursorPosition(0)
        self.actionMaskLineEdit.setObjectName(_fromUtf8("actionMaskLineEdit"))
        self.gridLayout_9.addWidget(self.actionMaskLineEdit, 9, 1, 1, 1)
        self.argumentLabel = QtGui.QLabel(self.ruleSettingsGroupBox)
        self.argumentLabel.setObjectName(_fromUtf8("argumentLabel"))
        self.gridLayout_9.addWidget(self.argumentLabel, 7, 0, 1, 1)
        self.ruleConditionLabel = QtGui.QLabel(self.ruleSettingsGroupBox)
        self.ruleConditionLabel.setObjectName(_fromUtf8("ruleConditionLabel"))
        self.gridLayout_9.addWidget(self.ruleConditionLabel, 1, 0, 1, 1)
        self.actionArgumentLineEdit = QtGui.QLineEdit(self.ruleSettingsGroupBox)
        self.actionArgumentLineEdit.setEnabled(False)
        self.actionArgumentLineEdit.setObjectName(_fromUtf8("actionArgumentLineEdit"))
        self.gridLayout_9.addWidget(self.actionArgumentLineEdit, 7, 1, 1, 1)
        self.ruleActionLabel = QtGui.QLabel(self.ruleSettingsGroupBox)
        self.ruleActionLabel.setObjectName(_fromUtf8("ruleActionLabel"))
        self.gridLayout_9.addWidget(self.ruleActionLabel, 0, 0, 1, 1)
        self.ruleCondComboBox = QtGui.QComboBox(self.ruleSettingsGroupBox)
        self.ruleCondComboBox.setEnabled(False)
        self.ruleCondComboBox.setObjectName(_fromUtf8("ruleCondComboBox"))
        self.gridLayout_9.addWidget(self.ruleCondComboBox, 1, 1, 1, 1)
        self.ruleTypeComboBox = QtGui.QComboBox(self.ruleSettingsGroupBox)
        self.ruleTypeComboBox.setEnabled(False)
        self.ruleTypeComboBox.setObjectName(_fromUtf8("ruleTypeComboBox"))
        self.gridLayout_9.addWidget(self.ruleTypeComboBox, 0, 1, 1, 1)
        self.conditionMaskLineEdit = QtGui.QLineEdit(self.ruleSettingsGroupBox)
        self.conditionMaskLineEdit.setEnabled(False)
        self.conditionMaskLineEdit.setObjectName(_fromUtf8("conditionMaskLineEdit"))
        self.gridLayout_9.addWidget(self.conditionMaskLineEdit, 4, 1, 1, 1)
        self.conditionMaskLabel = QtGui.QLabel(self.ruleSettingsGroupBox)
        self.conditionMaskLabel.setObjectName(_fromUtf8("conditionMaskLabel"))
        self.gridLayout_9.addWidget(self.conditionMaskLabel, 4, 0, 1, 1)
        self.conditionTargetMessageIdLabel = QtGui.QLabel(self.ruleSettingsGroupBox)
        self.conditionTargetMessageIdLabel.setObjectName(_fromUtf8("conditionTargetMessageIdLabel"))
        self.gridLayout_9.addWidget(self.conditionTargetMessageIdLabel, 2, 0, 1, 1)
        self.secondConditionValueLabel = QtGui.QLabel(self.ruleSettingsGroupBox)
        self.secondConditionValueLabel.setObjectName(_fromUtf8("secondConditionValueLabel"))
        self.gridLayout_9.addWidget(self.secondConditionValueLabel, 9, 0, 1, 1)
        self.conditionValueLineEdit = QtGui.QLineEdit(self.ruleSettingsGroupBox)
        self.conditionValueLineEdit.setEnabled(False)
        self.conditionValueLineEdit.setObjectName(_fromUtf8("conditionValueLineEdit"))
        self.gridLayout_9.addWidget(self.conditionValueLineEdit, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.ruleSettingsGroupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_9.addWidget(self.label_8, 3, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.ruleSettingsGroupBox)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.startMitmModeBtn = QtGui.QPushButton(self.actionsMITMTab)
        self.startMitmModeBtn.setObjectName(_fromUtf8("startMitmModeBtn"))
        self.horizontalLayout_5.addWidget(self.startMitmModeBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tabWidget_2.addTab(self.actionsMITMTab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.actionsTab, _fromUtf8(""))
        self.sdCardTab = QtGui.QWidget()
        self.sdCardTab.setObjectName(_fromUtf8("sdCardTab"))
        self.gridLayout_8 = QtGui.QGridLayout(self.sdCardTab)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.deleteFileBtn = QtGui.QPushButton(self.sdCardTab)
        self.deleteFileBtn.setObjectName(_fromUtf8("deleteFileBtn"))
        self.horizontalLayout_10.addWidget(self.deleteFileBtn)
        self.downloadFileBtn = QtGui.QPushButton(self.sdCardTab)
        self.downloadFileBtn.setObjectName(_fromUtf8("downloadFileBtn"))
        self.horizontalLayout_10.addWidget(self.downloadFileBtn)
        self.gridLayout_8.addLayout(self.horizontalLayout_10, 5, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_21 = QtGui.QLabel(self.sdCardTab)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_9.addWidget(self.label_21)
        self.sdCardFolderLineEdit = QtGui.QLineEdit(self.sdCardTab)
        self.sdCardFolderLineEdit.setObjectName(_fromUtf8("sdCardFolderLineEdit"))
        self.horizontalLayout_9.addWidget(self.sdCardFolderLineEdit)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.updateSdCardBtn = QtGui.QPushButton(self.sdCardTab)
        self.updateSdCardBtn.setObjectName(_fromUtf8("updateSdCardBtn"))
        self.horizontalLayout_9.addWidget(self.updateSdCardBtn)
        self.gridLayout_8.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.sdCardListWidget = QtGui.QListWidget(self.sdCardTab)
        self.sdCardListWidget.setObjectName(_fromUtf8("sdCardListWidget"))
        self.gridLayout_8.addWidget(self.sdCardListWidget, 1, 0, 1, 1)
        self.tabWidget.addTab(self.sdCardTab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionLoad_config = QtGui.QAction(MainWindow)
        self.actionLoad_config.setObjectName(_fromUtf8("actionLoad_config"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.connectedNodesListWidget, self.visibleNodesListWidget)
        MainWindow.setTabOrder(self.visibleNodesListWidget, self.connectDisconnectNodeBtn)
        MainWindow.setTabOrder(self.connectDisconnectNodeBtn, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.debugLogPlainTextEdit)
        MainWindow.setTabOrder(self.debugLogPlainTextEdit, self.nodeIdLineEdit)
        MainWindow.setTabOrder(self.nodeIdLineEdit, self.saveNodeSettingsBtn)
        MainWindow.setTabOrder(self.saveNodeSettingsBtn, self.tabWidget_2)
        MainWindow.setTabOrder(self.tabWidget_2, self.filterFramesByIdLineEdit)
        MainWindow.setTabOrder(self.filterFramesByIdLineEdit, self.filterFramesByIdCheckbox)
        MainWindow.setTabOrder(self.filterFramesByIdCheckbox, self.filterFramesByNewFramesAfterCheckbox)
        MainWindow.setTabOrder(self.filterFramesByNewFramesAfterCheckbox, self.filterFramesAfterNSpinBox)
        MainWindow.setTabOrder(self.filterFramesAfterNSpinBox, self.canLogTableView)
        MainWindow.setTabOrder(self.canLogTableView, self.startCanLoggerBtn)
        MainWindow.setTabOrder(self.startCanLoggerBtn, self.replayRemoveFrameBtn)
        MainWindow.setTabOrder(self.replayRemoveFrameBtn, self.addReplayFrameBtn)
        MainWindow.setTabOrder(self.addReplayFrameBtn, self.replayFramesTableView)
        MainWindow.setTabOrder(self.replayFramesTableView, self.replayFrameIdLineEdit)
        MainWindow.setTabOrder(self.replayFrameIdLineEdit, self.replayPayloadLineEdit)
        MainWindow.setTabOrder(self.replayPayloadLineEdit, self.startReplayBtn)
        MainWindow.setTabOrder(self.startReplayBtn, self.securityHijackSecurityLevelSpinBox)
        MainWindow.setTabOrder(self.securityHijackSecurityLevelSpinBox, self.securityHijackToolIdLineEdit)
        MainWindow.setTabOrder(self.securityHijackToolIdLineEdit, self.securityHijackNoOfAuthsToSkipSpinBox)
        MainWindow.setTabOrder(self.securityHijackNoOfAuthsToSkipSpinBox, self.securityHijackTargetIdLineEdit)
        MainWindow.setTabOrder(self.securityHijackTargetIdLineEdit, self.securityHijackUDSRadioButton)
        MainWindow.setTabOrder(self.securityHijackUDSRadioButton, self.securityHijackTPRadioButton)
        MainWindow.setTabOrder(self.securityHijackTPRadioButton, self.startSecurityHijackBtn)
        MainWindow.setTabOrder(self.startSecurityHijackBtn, self.udsActionsComboBox)
        MainWindow.setTabOrder(self.udsActionsComboBox, self.udsOwnIdLineEdit)
        MainWindow.setTabOrder(self.udsOwnIdLineEdit, self.udsTargetIdLineEdit)
        MainWindow.setTabOrder(self.udsTargetIdLineEdit, self.newUDSSessionBtn)
        MainWindow.setTabOrder(self.newUDSSessionBtn, self.udsLogPlainTextEdit)
        MainWindow.setTabOrder(self.udsLogPlainTextEdit, self.tpActionsComboBox)
        MainWindow.setTabOrder(self.tpActionsComboBox, self.tpChannelNegotIdLineEdit)
        MainWindow.setTabOrder(self.tpChannelNegotIdLineEdit, self.tpModuleIdLineEdit)
        MainWindow.setTabOrder(self.tpModuleIdLineEdit, self.newTPSessionBtn)
        MainWindow.setTabOrder(self.newTPSessionBtn, self.tpLogPlainTextEdit)
        MainWindow.setTabOrder(self.tpLogPlainTextEdit, self.saveRulesBtn)
        MainWindow.setTabOrder(self.saveRulesBtn, self.removeRuleBtn)
        MainWindow.setTabOrder(self.removeRuleBtn, self.addRuleBtn)
        MainWindow.setTabOrder(self.addRuleBtn, self.rulesTableView)
        MainWindow.setTabOrder(self.rulesTableView, self.ruleTypeComboBox)
        MainWindow.setTabOrder(self.ruleTypeComboBox, self.ruleCondComboBox)
        MainWindow.setTabOrder(self.ruleCondComboBox, self.conditionMessageIdLineEdit)
        MainWindow.setTabOrder(self.conditionMessageIdLineEdit, self.conditionValueLineEdit)
        MainWindow.setTabOrder(self.conditionValueLineEdit, self.conditionMaskLineEdit)
        MainWindow.setTabOrder(self.conditionMaskLineEdit, self.actionArgumentLineEdit)
        MainWindow.setTabOrder(self.actionArgumentLineEdit, self.actionMaskLineEdit)
        MainWindow.setTabOrder(self.actionMaskLineEdit, self.startMitmModeBtn)
        MainWindow.setTabOrder(self.startMitmModeBtn, self.deleteFileBtn)
        MainWindow.setTabOrder(self.deleteFileBtn, self.downloadFileBtn)
        MainWindow.setTabOrder(self.downloadFileBtn, self.sdCardFolderLineEdit)
        MainWindow.setTabOrder(self.sdCardFolderLineEdit, self.updateSdCardBtn)
        MainWindow.setTabOrder(self.updateSdCardBtn, self.sdCardListWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "CanBadger Server", None))
        self.label_2.setText(_translate("MainWindow", "Connected Nodes:", None))
        self.label.setText(_translate("MainWindow", "Disconnected Nodes:", None))
        self.connectDisconnectNodeBtn.setText(_translate("MainWindow", "Connect", None))
        self.statusInformationGroupBox.setTitle(_translate("MainWindow", "Status Information", None))
        self.lastIdBroadcastLabel.setText(_translate("MainWindow", "Last ID Broadcast:", None))
        self.lastIdBroadcastIndicator.setText(_translate("MainWindow", "#value", None))
        self.debugLogGroupBox.setTitle(_translate("MainWindow", "Debug Log", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.statusTab), _translate("MainWindow", "Status", None))
        self.nodeIdEditLabel.setText(_translate("MainWindow", "Node ID:", None))
        self.label_10.setText(_translate("MainWindow", "After saving, you should reset the CanBadger by clicking \"Disconnect\"!", None))
        self.saveNodeSettingsBtn.setText(_translate("MainWindow", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.nodeSettingsTab), _translate("MainWindow", "Node Settings", None))
        self.filterFramesGroupBox.setTitle(_translate("MainWindow", "Filter Frames", None))
        self.filterFramesByIdLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Filter by frame id.</p><p>You can enter multiple IDs, separated by comma.</p><p><br/></p><p>Example: 0080,0081</p></body></html>", None))
        self.filterFramesByIdCheckbox.setText(_translate("MainWindow", "by ID", None))
        self.filterFramesByNewFramesAfterCheckbox.setText(_translate("MainWindow", "only new IDs after", None))
        self.filterFramesAfterNSpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Show only frames from new IDs that are recorded after $value frames</p></body></html>", None))
        self.canLogSettingsGroupBox.setTitle(_translate("MainWindow", "Logging Options", None))
        self.canLogOnPort1RadioBtn.setText(_translate("MainWindow", "Log on Port 1", None))
        self.canLogOnPort2RadioBtn.setText(_translate("MainWindow", "Log on Port 2", None))
        self.passThruModeCheckBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Pass-Thru mode will forward any packets from one port to another. This way, traffic is logged but not altered.</p></body></html>", None))
        self.passThruModeCheckBox.setText(_translate("MainWindow", "Pass-Thru Mode", None))
        self.saveCanLogBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Save logged frames to a JSON file</p></body></html>", None))
        self.saveCanLogBtn.setText(_translate("MainWindow", "...", None))
        self.startCanLoggerBtn.setText(_translate("MainWindow", "Start Logging", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.actionsCanLoggerTab), _translate("MainWindow", "Logger", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Frame Sequence", None))
        self.replayMoveUpBtn.setText(_translate("MainWindow", "↑", None))
        self.replayMoveDownBtn.setText(_translate("MainWindow", "↓", None))
        self.replayRemoveFrameBtn.setText(_translate("MainWindow", "Remove", None))
        self.addReplayFrameBtn.setText(_translate("MainWindow", "Add", None))
        self.groupBox.setTitle(_translate("MainWindow", "Modify Frame", None))
        self.label_19.setText(_translate("MainWindow", "ID", None))
        self.label_20.setText(_translate("MainWindow", "Payload (HEX)", None))
        self.startReplayBtn.setText(_translate("MainWindow", "Start Replay", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.actionsReplayTab), _translate("MainWindow", "Replay", None))
        self.label_12.setText(_translate("MainWindow", "No. of Authentications to Skip:", None))
        self.securityHijackStatusIndictor.setText(_translate("MainWindow", "# status", None))
        self.label_5.setText(_translate("MainWindow", "Security Level", None))
        self.label_4.setText(_translate("MainWindow", "Target ID", None))
        self.securityHijackUDSRadioButton.setText(_translate("MainWindow", "UDS", None))
        self.securityHijackTPRadioButton.setText(_translate("MainWindow", "TP", None))
        self.startSecurityHijackBtn.setText(_translate("MainWindow", "Start Hijack", None))
        self.label_3.setText(_translate("MainWindow", "Tool ID", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.actionsSecurityAccessTab), _translate("MainWindow", "Security Hijack", None))
        self.label_6.setText(_translate("MainWindow", "Actions", None))
        self.label_16.setText(_translate("MainWindow", "Target ID:", None))
        self.label_15.setText(_translate("MainWindow", "Own ID:", None))
        self.udsOwnIdLineEdit.setText(_translate("MainWindow", "7e0", None))
        self.udsTargetIdLineEdit.setText(_translate("MainWindow", "7e8", None))
        self.newUDSSessionBtn.setText(_translate("MainWindow", "New Session", None))
        self.label_13.setText(_translate("MainWindow", "Log", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.actionsUDSTab), _translate("MainWindow", "UDS", None))
        self.label_7.setText(_translate("MainWindow", "Actions", None))
        self.label_17.setText(_translate("MainWindow", "Channel Negotiation ID", None))
        self.label_18.setText(_translate("MainWindow", "Module ID", None))
        self.newTPSessionBtn.setText(_translate("MainWindow", "New Session", None))
        self.label_14.setText(_translate("MainWindow", "Log", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.actionsTPTab), _translate("MainWindow", "TP", None))
        self.rulesGroupBox.setTitle(_translate("MainWindow", "Rules", None))
        self.loadRulesFromFileBtn.setToolTip(_translate("MainWindow", "Load rules from a json file", None))
        self.loadRulesFromFileBtn.setText(_translate("MainWindow", "Load from File", None))
        self.saveRulesToFileBtn.setToolTip(_translate("MainWindow", "Save rules to a json file", None))
        self.saveRulesToFileBtn.setText(_translate("MainWindow", "Save to file", None))
        self.saveRulesBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Save Rules so the MITM mode will use them</p></body></html>", None))
        self.saveRulesBtn.setText(_translate("MainWindow", "Save Rules to SD", None))
        self.removeRuleBtn.setText(_translate("MainWindow", "Remove", None))
        self.addRuleBtn.setText(_translate("MainWindow", "Add", None))
        self.ruleSettingsGroupBox.setTitle(_translate("MainWindow", "Rule Settings", None))
        self.conditionMessageIdLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>The frame id will always be matched against this value</p></body></html>", None))
        self.actionMaskLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Bytemask for the rule actions that require specific bytes:</p><p>A 1 will match a byte and a 0 will ignore the byte. (Leftmost ist MSB)</p></body></html>", None))
        self.argumentLabel.setText(_translate("MainWindow", "Action Argument:", None))
        self.ruleConditionLabel.setText(_translate("MainWindow", "Condition:", None))
        self.ruleActionLabel.setText(_translate("MainWindow", "Action:", None))
        self.ruleCondComboBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Condition:</p><p>Frames are first matched by ID and then, it will try to match the condition specified here.</p></body></html>", None))
        self.conditionMaskLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Bytemask for the rule condition:</p><p>A 1 will match a byte and a 0 will ignore the byte. (Leftmost ist MSB)</p></body></html>", None))
        self.conditionMaskLabel.setText(_translate("MainWindow", "Condition Mask:", None))
        self.conditionTargetMessageIdLabel.setText(_translate("MainWindow", "Target Frame ID:", None))
        self.secondConditionValueLabel.setText(_translate("MainWindow", "Action Mask", None))
        self.label_8.setText(_translate("MainWindow", "Condition Value:", None))
        self.startMitmModeBtn.setText(_translate("MainWindow", "Start MITM", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.actionsMITMTab), _translate("MainWindow", "MITM", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.actionsTab), _translate("MainWindow", "Actions", None))
        self.deleteFileBtn.setText(_translate("MainWindow", "Delete File", None))
        self.downloadFileBtn.setText(_translate("MainWindow", "Download File", None))
        self.label_21.setText(_translate("MainWindow", "Folder:", None))
        self.sdCardFolderLineEdit.setText(_translate("MainWindow", "/sd", None))
        self.updateSdCardBtn.setText(_translate("MainWindow", "Update", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sdCardTab), _translate("MainWindow", "SD Card", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionLoad_config.setText(_translate("MainWindow", "Load config", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))

from can_log_table_view import CanLogTableView
